supabase/wrappers

.github/workflows/release.yml, Cargo.lock, supabase-wrappers-macros/src/instance.rs, supabase-wrappers-macros/src/modify.rs, supabase-wrappers-macros/src/polyfill.rs, supabase-wrappers-macros/src/qual.rs, supabase-wrappers-macros/src/scan.rs, supabase-wrappers-macros/src/utils.rs, supabase-wrappers/Cargo.toml, supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, supabase-wrappers/src/utils.rs, wrappers/.ci/docker-compose.yaml, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/bin/installcheck, wrappers/dockerfiles/pg/Dockerfile, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
Problem: wrappers uses pgx 0.5.6
This version is outdated.
Solution: upgrade to 0.6.0
I've also set the default version of Postgres to 15 as pgx supports it now and this is the most recent version that keeps evolving, therefore it would be better to track it to catch new failures.
Dependency update
Using pgx 0.5.6
Using pgx 0.6.0
=> Upgrade pgx to 0.6.0

README.md, supabase-wrappers-macros/README.md, supabase-wrappers/README.md
This PR is to fix badge link and fix typo in docs.
N/A
N/A
N/A
=> docs: change badge link and fix typo

wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
This PR is to add more smoke test cases for Stripe FDW.
Currently, there are only 3 test cases:
1. Balance
2. Customers
3. Subscriptions
More test cases will be added:
1. Balance
2. Balance Transactions
3. Charges
4. Customers
5. Invoices
6. PaymentIntents
7. Products
8. Subscriptions
N/A
=> chore: add more Stripe test cases

README.md, supabase-wrappers/README.md, wrappers/Cargo.lock
This PR is to add docs for required function `new()` and also update wrappers version in Cargo.lock file.
Required `new()` function is missing in READMEs.
Add missing `new()` function docs.
N/A
=> docs: add docs for new() and update Cargo.lock

wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs
This PR is to add float data type support bigquery fdw.
Currently it cannot read `Float/Float64` data type from BigQuery.
It should be able to read `Float/Float64` data types.
N/A
=> fix: add float type support for bigquery fdw

README.md
Docs Update
Assuming this is supposed to be the SQL `WHERE` keyword.
N/A
N/A
N/A
=> Fix typo on README s/WEHRE/WHERE/

supabase-wrappers/src/scan.rs
Fix preventing the backend from crashing when `EXPLAIN ANALYZE` is used on a FDW query with nontrivial quals.
Backend crashes due to plan memory being allocated in a temporary memory context.
`explain_foreign_scan` allocates the plan in the query (caller's) memory context, thus ensuring it lives long enough.
Fixes https://github.com/supabase/wrappers/issues/45
=> :fix: allocate plan in query memory context

supabase-wrappers/src/interface.rs, supabase-wrappers/src/scan.rs
A new iter_scan method to reuse a borrowed `Row`; a few additional performance improvements.
`ForeignDataWrapper::iter_scan` requires the implementor to build a Row, which is quite expensive.
`ForeignDataWrapper::iter_scan_borrowed` takes a mutable ref to a Row owned by the caller; the implementor just needs to populate it.
A default implementation is provided that simply delegates to `ForeignDataWrapper::iter_scan` and swaps the returned `Row`.
On my machine (intel 8700k), in release mode, pg15, with a sample FDW that yields 10M "helloworld" rows, the time taken to execute `SELECT * FROM bench WHERE id < 0` are:
* Original: 3244,732 ms (00:03,245)
* Without `debug2!` on `iter_scan`: 1565,417 ms (00:01,565)
* Reusing `Row`: 1241,977 ms (00:01,242)
I've been unable to run the tests on …
=> Perf improvements

supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, supabase-wrappers/src/scan.rs, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/helloworld_fdw/helloworld_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to use borrowed `row` in `iter_scan()` to improve performance, see #46 .
Currently in each call of the `iter_scan()` function, an empty new row needs to be created and values are copied over to Postgres, this can be slow when reading large number of rows.
The new `iter_scan()` function will pass a pre-allocated `row` and FDW can optionally use `mem::replace()` to directly move data in.
See more details in #46 .
=> chore: use borrowed row in iter_scan()

docs/stripe.md, wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
This PR is to add and improve 3 [Stripe Connect objects](https://stripe.com/docs/api/accounts):
- Accounts
- Top-ups (new)
- Transfers
Currently there are only 2 Stripe Connect objects: `Accounts` and `Transfers`.
Added a new object `Top-ups` and also added test cases and documents.
N/A
=> feat: add more Stripe Connect objects

wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
Fix #57 
The `attrs` column order is wrongly placed in target column list, so queries like below returns empty.
```
select attrs from stripe.charges where id = 'ch_3MZiaiI3rSV8HFQa0lzuJV2I';
```
Tha `attrs` column order should be correct so the query above can work correctly.
N/A
=> fix: modify stripe attrs column order, fix #57

Cargo.lock, supabase-wrappers-macros/Cargo.toml, supabase-wrappers/Cargo.toml, supabase-wrappers/src/interface.rs, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/bigquery_fdw/README.md, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/bigquery_fdw/tests.rs
This PR is to add result pagination and `order` and 'limit' pushdown for BigQuery FDW.
The BQ FDW currently can only read one page of data which is not more than 10MB, thus caused incorrect result if the source dataset is large. Also there is no  which caused slow queries.
Result pagination and `order` and `limit` pushdown have been added.
N/A
=> feat: add pagination and pushdown for bq fdw

supabase-wrappers/src/interface.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/bigquery_fdw/tests.rs
This PR is to fix a bug when deparsing multiple sorts.
When the `order by` have multiple columns, the deparsed sql is like `order by x order by y` which is incorrect.
The `Sort::deparse()` outputs sql without `order by`, which should be done in fdw.
N/A
=> fix: fix multiple sorts deparse

supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, supabase-wrappers/src/scan.rs, supabase-wrappers/src/utils.rs, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/airtable_fdw/result.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/helloworld_fdw/helloworld_fdw.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to enrich the target `column` in interface.
Currently, the `column` in interface is simply a column name string without other metadata, which is limited in some cases. 
The `column` now is enriched to a struct with 3 properties:
- `name` - column name
- `num` - column number in table definition, 1-based
- `type_oid` - column type OID
This is a breaking change as it changed the foreign data wrapper interface, all FDWs need to adopt this change.
=> feat: enrich target column in interface

README.md, supabase-wrappers/README.md, supabase-wrappers/src/utils.rs
This PR is to exclude generated column from target columns, so to fix #71 .
The generated column is not supported yet, but it currently reports an error when using it.
Although generated column is not supported, it should report a warning instead an error.
N/A
=> fix: exclude generated column

wrappers/src/fdw/bigquery_fdw/README.md, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/bigquery_fdw/tests.rs
This PR is to add subquery support to `table` option in BigQuery FDW, possibly fix #69 and #70 . 
Currently, the `table` foreign table option in BigQuery FDW can only specify a table or view name, which limits the fdw usage in some cases.
In the `table` option we can specify a subquery enclosed in parentheses. For example,
```sql
OPTIONS (
table '(select * except(props), to_json_string(props) as props from `my_project.my_dataset.my_table`)'
)
```
As the [dependent lib](https://docs.rs/gcp-bigquery-client/latest/gcp_bigquery_client/model/field_type/enum.FieldType.html) doesn't support JSON type at this moment, this feature can be used as a workaround to read JSON data from BQ.
=> feat: add subquery to bq fdw table option

wrappers/src/fdw/airtable_fdw/result.rs
Introduces feature that allows Airtable FDW to handle `Object` and `Array` types from Airtable API.
FDW is not currently able to map Airtable `Object` / `Array` types to postgres. If it is attempted, the FDW handler raises a panic.
Airtable `Object` and `Array` types are mapped to `pgx::JsonB`. This means that these types must be mapped to a `jsonb` postgres column data type.
These types are especially useful, as this now allows users to handle Airtable types such as:
- Image
- Link to another record
This is by no means bulletproof (I am a Rust noob) or necessarily able to handle every Airtable type that maps to array / object, but it is certainly better than not being able to handle any of these Airtable types at all.
=> Add Array/Object type handling to Airtable wrapper

docs/bigquery.md, supabase-wrappers/src/interface.rs, wrappers/dockerfiles/bigquery/data.yaml, wrappers/src/fdw/bigquery_fdw/README.md, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/bigquery_fdw/tests.rs
This PR added below 2 features to BigQuery FDW:
1. `NUMERIC` data type support
2. `timeout` foreign table option
1. There is no support for `NUMERIC` data type. See details: https://github.com/supabase/wrappers/issues/70#issuecomment-1493418694
2. Current query request timeout is 10 seconds, it will return empty result if it expired.
1. `NUMERIC` data type is supported
2. Default query request timeout is 30 seconds and can be adjusted by foreign table option `timeout`, will also raise error if timeout expired.
N/A
=> feat: add numeric type support and timeout option for bq fdw

supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, supabase-wrappers/src/memctx.rs, supabase-wrappers/src/modify.rs, supabase-wrappers/src/qual.rs, supabase-wrappers/src/scan.rs, supabase-wrappers/src/utils.rs
This PR is to add support for prepared statement, which uses query parameters. PostgREST uses the prepared statement to access foreign table, without this support PostgREST will fail after several successful accesses. This PR will fix #56 .
There is no support for prepared statement, it will cause unexpected result when use it to access foreign tables several times.
For example, create a prepared statement like below,
```sql
prepare get_product(text) as select id, name from products where id=$1;
```
and then repeat query it with parameter value,
```sql
execute get_product('prod_NuECg9VTeI3IIJ');
```
This will produce correct `quals` to FDW in the first several queries, but later queries will get empty `quals`. The reason is because Postgres does some optimisations for repeated query, …
=> fix: add prepared statement support

wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
The `404` request error should be considered as an empty result, not a request error.
Currently, `404` error is treated as a request error, like other http request errors.
`404` error will be treated as returning an empty result set.
N/A
=> chore: stripe fdw treat 404 error as empty result

docs/clickhouse.md, supabase-wrappers/src/interface.rs, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is mainly to add custom sql support `table` option, also with some improvements.
Currently, the custom sql isn't supported.
- `table` option now can support custom sql
- added `UInt16` and `Date` type support
- custom sql can support Parametrized view
- made `rowid_column` optional for read-only foreign table
N/A
=> feat: add custom sql support for clickhouse fdw

docs/stripe.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
Adding checkout sessions to the Stripe FDW. For those wondering why this object before others, my particular use case needs to get at custom field data captured on checkout. Happy to help build out more objects once I make sure I'm doing this correctly.
This PR is currently WIP. I need to resolve running the tests locally, and documentation updates. So far I'm getting errors that indicate no data when running. Documentation on testing under contrib is out of date as well
```sh
docker-compose -f wrappers/.ci/docker-compose.yaml up -d
cargo pgx test pg15 --features stripe_fdw
```
Not implemented
Enables
```sql
create foreign table stripe.checkout_sessions (
id text,
customer text,
payment_intent text,
subscription text,
attrs jsonb
)
server stripe_server
options (
object …
```
=> Stripe FDW: Adding checkout sessions

supabase-wrappers/src/interface.rs
This PR is to add compatible types for `Cell`, so the [FromDatum](https://docs.rs/pgrx/0.8.3/pgrx/datum/trait.FromDatum.html#) trait can be used with it. This `is_compatible_with()` function is enforced in `FromDatum` from pgrx v0.8.3, so we have to define it.
Currently, the `FromDatum` trait of `Cell` cannot work properly.
The `FromDatum` trait of `Cell` can work as expected.
N/A
=> fix: add cell compatible types

.github/workflows/release.yml, .github/workflows/test_wrappers.yml, Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, supabase-wrappers/src/qual.rs, supabase-wrappers/src/sort.rs, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/s3_fdw/parquet.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to upgrade `pgrx` to v0.9.6.
Currently, the dependency `pgrx` is on v0.8.3.
`pgrx` is upgraded on v0.9.6.
In pgrx v0.9.6 there are some datetime related helper functions added, so we adjust the fdw codes accordingly.
=> chore: upgrade to pgrx 0.9.6

.github/workflows/release.yml, .github/workflows/test_wrappers.yml, Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/src/lib.rs, wrappers/Cargo.lock, wrappers/Cargo.toml
A critical bug concerning handling arrays with an initial null element was discovered in pgrx versions 0.8.0 to 0.9.6, recommending an upgrade to 0.9.7 as soon as is possible.
=> Update to pgrx 0.9.7

wrappers/sql/bootstrap.sql, wrappers/sql/finalize.sql, wrappers/src/fdw/airtable_fdw/README.md, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/bigquery_fdw/README.md, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/README.md, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/README.md, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/s3_fdw/README.md, wrappers/src/fdw/s3_fdw/parquet.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs, wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/lib.rs, wrappers/src/stats.rs
This PR is add stats collection facilities to all FDWs, which is to improve FDW usage observability.
A new stats table `wrappers_fdw_stats` will be created when Wrappers extension installed.
```sql
CREATE TABLE wrappers_fdw_stats (
fdw_name          text NOT NULL PRIMARY KEY,
create_times      bigint NULL,
rows_in           bigint NULL,
rows_out          bigint NULL,
bytes_in          bigint NULL,
bytes_out         bigint NULL,
metadata          jsonb NULL,
created_at        timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
updated_at        timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);
COMMENT ON TABLE wrappers_fdw_stats IS 'Wrappers Foreign Data Wrapper statistics';
COMMENT ON COLUMN wrappers_fdw_stats.create_times IS 'Total number of times the FDW instacne has …
```
=> feat: add fdw stats collection

wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
This implements pushdown for `ORDER BY` and `LIMIT` (and `OFFSET`) mostly taken from the bigquery FDW.
=> Implement sort and limit pushdown for clickhouse

wrappers/src/fdw/clickhouse_fdw/README.md, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is to clean clickhouse fdw source and bump version.
N/A
N/A
N/A
=> chore: format clickhouse fdw code and bump version

wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
Bug fix
`SELECT`ing with `WHERE` clause that only contains the parameter from the parametrized SQL table definition was inserting a spurious `WHERE` without any clause. 
Checks for empty conditions and only adds `WHERE` when appropriate.
Also adds some tests.
=> Fix WHERE pushdown with parametrized SQL as table clickhouse FDW

docs/clickhouse.md
This PR is to add connection string examples and doc link for ClickHouse FDW server option.
N/A
N/A
N/A
=> docs: add clickhouse connection string examples and doc link

docs/airtable.md, docs/bigquery.md, docs/clickhouse.md, docs/firebase.md, docs/logflare.md, docs/s3.md, docs/stripe.md
This PR is to update docs for storing FDW credentials in line with latest Supabase Vault.
Currently the docs are still using `pgsodium` to store FDW credentials.
Use latest `Vault` to store FDW credentials.
N/A
=> docs: update vault credentials docs

docs/stripe.md
Docs update
Cannot query stripe prices table after creating the table following the guide from supabase docs. When querying the following error is returned.
```object "pricing" not implemented.```
The table can now be queried and stripe price data are returned.
I am developing in stripe test mode with strip test api keys.
=> Foreign data wrapper with stripe docs update

Cargo.lock, docs/bigquery.md, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs
This PR is to fix BigQuery FDW data modify issue, which will fix #124 .
This issue is caused by upstream BigQuery client lib change, so this PR will also upgrade to latest version of `gcp-bigquery-client`.
The BigQuery FDW can only read data, but not modify data (insert, update and delete).
The BigQuery FDW will be able to modify data.
N/A
=> fix: bigquery fdw data modify

docs/airtable.md, wrappers/dockerfiles/airtable/server.py, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/airtable_fdw/tests.rs
This PR is to add support for [Airtable View](https://support.airtable.com/docs/view-basics), which was requested in #133. 
The current Airtable fdw only supports `table`, `view` is not supported.
Airtable View is supported by a new foreign table option `view_id`.
N/A
=> feat: add view support for airtable fdw

wrappers/Cargo.lock, wrappers/Cargo.toml
This PR is to upgrade some deps to remove [the webpki alert](https://github.com/supabase/wrappers/security/dependabot/20)
There is an alert for using older version of `webpki`.
The `webpki` dependency will be removed.
N/A
=> chore: upgrade deps to remove webpki alert

README.md
Remove a redundant word in README
=> remove redundant word

supabase-wrappers/src/scan.rs
Fixed following warning:
```
warning: casting raw pointers to the same type and constness is unnecessary (`*mut pgrx::pgrx_pg_sys::EState` -> `*mut pgrx::pgrx_pg_sys::EState`)
```
=> fix a clippy warning

wrappers/src/stats.rs
When running `cargo pgrx run --features helloworld_fdw` as described in `helloworld_fdw`'s README, got the following warning:
```
warning: function `inc_stats` is never used
--> src/stats.rs:44:15
|
44 | pub(crate) fn inc_stats(fdw_name: &str, metric: Metric, inc: i64) {
|               ^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
Added a `#[allow(dead_code)]` attribute to suppress this.
=> fix unused warning

Cargo.toml
Set [workspace resolver version](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) to 2 to fix the following warning while `cargo build`ing:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
=> set workspace resolver version to 2

wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/mod.rs
This PR removes dependency on `cfg-if` crate because it is not needed.
=> Remove cfg_if dependency

supabase-wrappers-macros/src/lib.rs, supabase-wrappers/src/instance.rs, supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, supabase-wrappers/src/modify.rs, supabase-wrappers/src/scan.rs, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/helloworld_fdw/helloworld_fdw.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
Refactoring
The `ForeignDataWrapper` trait's methods do not return `Result`s even though they are fallible. This results in forcing the user to call `unwrap` or `expect`, instead of the more ergonomic alternative of returning an `Err`.
The `ForeignDataWrapper` trait's methods will now return a `Result`. The error types should be convertible into an `ErrorReport`, i.e. they should `impl From<ErrorType> for ErrorReport` for the FDW's `ErrorType`. An `ErrorReport` is a `pgrx` type to represent errors which can be reported to Postgres. The errors returned by the trait's methods will be automatically reported to Postgres by the `supabase-wrappers` framework.
An example FDW with the new API looks something like this:
```rust
/// The error type has to be specified in the `error_type` field of …
```
=> Fallible ForeignDataWrapper trait methods

Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/src/utils.rs, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
Fix
The `create_async_runtime` method calls `unwrap` which swallows the real error.
The `create_async_runtime` method not longer calls `unwrap`. Full error is no preserved and reported.
This is the first of many PRs which will benefit from the change in API introduced in #144. `thiserror` has also been added to make errors easier to handle.
=> fix: remove unwrap in `create_async_runtime`

Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/src/utils.rs, wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/airtable_fdw/mod.rs, wrappers/src/fdw/airtable_fdw/result.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to use the new error reporting facilities in wrappers framework to refactor Airtable FDW.
Error reporting is using new facilities in wrappers framework for Airtable FDW.
N/A
=> chore(airtable_fdw): refactor error reporting

docs/airtable.md
In reference to [this issue](https://github.com/supabase/wrappers/issues/159), clarified how to set Airtable's PAT in the wrapper.
=> docs: clarify how to set airtable PAT

.github/workflows/release.yml
ARM runner is not able to build pgrx extensions in 45 minutes anymore. Bumping to 90
=> Bump release timeout due to failed arm builds

.github/workflows/release.yml, wrappers/Cargo.lock, wrappers/Cargo.toml
Bump version to prepare for release.
=> chore: bump version to 0.1.17

.github/workflows/release.yml, wrappers/Cargo.toml, wrappers/dockerfiles/airtable/server.py, wrappers/src/fdw/airtable_fdw/result.rs, wrappers/src/fdw/airtable_fdw/tests.rs
You were right @imor, lets allow any valid json, as I just noticed that this is already the behaviour of BigQuery FDW, so let's not diverge here.
Upgrade Wrappers from `v0.0.17` to `v0.0.18`.
=> ref: Make jsonb type work with any valid json and add more tests to cover it

wrappers/Cargo.lock, wrappers/src/stats.rs
Bug fix
If a query on a foreign table was done in a read-only transaction, it failed with this error:
```
ERROR:  cannot execute INSERT in a read-only transaction
CONTEXT:  SQL statement "insert into public.wrappers_fdw_stats as s (fdw_name, create_times) values($1, $2)
on conflict(fdw_name)
do update set
create_times = coalesce(s.create_times, 0) + excluded.create_times,
updated_at = timezone('utc'::text, now())"
```
This error occurred because `wrappers` updated `wrappers_fdw_stats` table for each query on a foreign table. `wrappers` will now update the `wrappers_fdw_stats` table only if the transaction is read-write.
N/A
=> fix: only update `wrappers_fdw_stats` table in a read-write transaction

wrappers/Cargo.lock, wrappers/Cargo.toml
This PR is to add missing `http` dependency for stripe and logflare fdw, which caused compilation error when compile fdw individually like below:
`cargo pgrx run --features stripe_fdw`
Compile stripe and logflare fdw will fail.
Compile stripe and logflare fdw is okay.
N/A
=> fix: compilation error for stripe and logflare fdw

docs/stripe.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to fix #113 . It will keep remote scan result and add implementation for `re_scan()` callback to reset iteration index when in nested loop join.
If the query joins 2 Stripe foreign tables, the result data isn't correct.
Stripe foreign table join should work correctly.
We may need to implement the same `re_scan()` callback for other FDWs to support join on foreign tables, but this PR only deals with Stripe FDW for now.
=> fix: incorrect stripe table join

.github/workflows/release.yml, wrappers/Cargo.lock, wrappers/Cargo.toml
To prepare a release which includes [this fix](https://github.com/supabase/wrappers/pull/188).
=> chore: bump version to 0.1.18

.github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, supabase-wrappers/Cargo.toml, supabase-wrappers/src/interface.rs, supabase-wrappers/src/limit.rs, supabase-wrappers/src/qual.rs, supabase-wrappers/src/sort.rs, wrappers/Cargo.lock, wrappers/Cargo.toml
pgrx 0.11 introduced a new API for the node type tags; they're enum members now.
this change replaces the old references with the enum refs
=> Update pgrx deps to 0.11.0

docs/airtable.md, docs/bigquery.md, docs/clickhouse.md, docs/firebase.md, docs/logflare.md, docs/s3.md, docs/stripe.md
This PR is to add schema name when creating wrappers extension, which is required on Supabase platform.
There is no schema specified when creating wrappers extension, so the default schema `public` is used but that caused RLS warning on Supabase platform.
The wrappers extension should be created in `extensions` schema.
N/A
=> docs: add extension creation schema

wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/s3_fdw/parquet.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to fix compilation warning for static string, which became warning since Rust 1.74.0.
N/A
N/A
N/A
=> fix: static str compilation warning

supabase-wrappers/src/interface.rs, supabase-wrappers/src/limit.rs
After merged PR #205, there are some compilation warnings in `supabase-wrappers`, we need to deal with them.
N/A
N/A
When upstream pgrx merged [this PR](https://github.com/pgcentralfoundation/pgrx/pull/1432), we need to remove the temporary warning stopper.
=> fix: update with pgrx upstream and remove compilation warning

README.md, docs/airtable.md, docs/bigquery.md, docs/clickhouse.md, docs/firebase.md, docs/index.md, docs/logflare.md, docs/s3.md, docs/stripe.md
docs update
Docs used GH specific markdown syntax to show emojis which did not render correctly on some sites like trunk. See this e.g.: https://pgt.dev/extensions/wrappers
We use unicode emojis which should be supported by more platforms because it is just unicode.
Fixes #211. The whitespace and other formatting changes are done automatically by vscode when saving a file.
=> use unicode emojis instead of GH markdown

wrappers/Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/s3_fdw/mod.rs, wrappers/src/fdw/s3_fdw/parquet.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs
There is an upgrade for S3 dependencies released which replaces some of the deprecated functions. Additionally, there are some shared dependencies between the [Cognito Identity Crate](https://crates.io/crates/aws-sdk-cognitoidentity) and the S3 FDW dependencies so upgrading the dependencies would simplify the implementation fo the Cognito wrapper
We are currently on v0
We move to v1 of the crates
=> feat: upgrade S3 FDW dependencies

.github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, supabase-wrappers/src/qual.rs, wrappers/src/fdw/auth0_fdw/auth0_client/rows_iterator.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/mod.rs, wrappers/src/fdw/stripe_fdw/tests.rs
This PR is mainly to add below 2 checking tasks to CI, these will enforce code formation and also make clippy happy.
- `cargo fmt`
- `cargo clippy`
Some code has been improved to make those 2 tasks working.
N/A
N/A
N/A
=> ci: add `cargo fmt` and `cargo clippy` checks to CI

docs/stripe.md
This PR is to add docs for the missing `api_url` Stripe FDW server option. Fix #219 
N/A
N/A
N/A
=> docs(stripe): add docs for `api_url` server option

wrappers/Cargo.toml
Pin clickhouse.rs to a fixed commit so that type or function signature changes in the library do not affect wrappers.
As only one of `branch` and `rev` can be used we drop the `branch` specifier.
=> feat: pin clickhouse.rs to fixed commit 

Cargo.lock, supabase-wrappers/Cargo.toml
This PR is to increase version number of supabase-wrappers to v0.1.16, so it can be released on crates.io.
N/A
N/A
N/A
=> chore: release supabase-wrappers v0.1.16 on crates.io

Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/README.md, supabase-wrappers/src/lib.rs
This PR is to increase version number of supabase-wrappers to v0.1.17 to fix docs building issue on docs.rs, so it can be released on crates.io.
N/A
N/A
N/A
=> chore: release supabase-wrappers v0.1.17 on crates.io

.github/workflows/test_wrappers.yml, Cargo.lock, wrappers/.ci/docker-compose.yaml, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is to remove db initialisation for ClickHouse FDW test, as it is not supported by the latest ClickHouse docker image and it is actually not needed to set up a new database.
The ClickHouse FDW test uses a database called `supa`.
It is no need to set up a new database for testing, just use the `default` db is enought.
This PR also updated the github action run command to remove warning `Ignoring feature 'clickhouse_fdw,pg15'`
=> ci: remove clickhouse init db

.github/workflows/test_wrappers.yml, Cargo.lock, wrappers/.ci/docker-compose.yaml, wrappers/src/fdw/clickhouse_fdw/tests.rs, wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/redis_fdw/redis_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to add state reset code when begin a scan, this can partially fix #237.
The foreign table scan execution plan will be cached when foreign table query is defined in a function, this will result in `begin_scan()` being called without calling `new()` function, which is supposed to re-initialise the FDW instance.
Added some state reseting codes in `begin_scan()` for some FDWs, so that their inner state will be reset correctly.
This PR can partially fix #237, so the continuous  foreign table function call should be correct. But for permanent fix, we need to find out better way to manage and re-use `FdwState`.
=> fix: reset state when begin scan

wrappers/src/fdw/s3_fdw/s3_fdw.rs
This PS is to add comment to state the reason why not use `create_async_runtime()` function.
N/A
N/A
N/A
=> chore(s3): add not use existing create_async_runtime() comment

docs/s3.md, wrappers/src/fdw/s3_fdw/s3_fdw.rs
Adds the option to provide `endpoint_url` when configuring an s3 server
Current behaviour does not allow this option and limits s3 functionality to AWS
Allows any s3 compatible providers to be used with the wrapper
Env var could not be used as it is [not supported in the SDK](https://github.com/awslabs/aws-sdk-rust/issues/932)
=> Add s3 endpoint support

wrappers/src/fdw/auth0_fdw/auth0_client/row.rs, wrappers/src/fdw/cognito_fdw/cognito_client/row.rs
Adds support for the "attributes" field so we can fetch [all attributes from the user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html)
=> fix: add attributes support for cognito wrapper

docs/auth0.md, wrappers/dockerfiles/auth0/server.py, wrappers/src/fdw/auth0_fdw/README.md, wrappers/src/fdw/auth0_fdw/auth0_client/mod.rs, wrappers/src/fdw/auth0_fdw/auth0_client/row.rs, wrappers/src/fdw/auth0_fdw/auth0_client/rows_iterator.rs, wrappers/src/fdw/auth0_fdw/auth0_fdw.rs
FLUP to #183 where we aim to introduce pagination on the user object. Auth0 has `pagination` by supplying the following fields:
- `total` - this is the total number of entries
-  `per_page` - this is the number of entries per page
- `page` - this is the current page we're on
Here are the [docs](https://auth0.com/docs/manage-users/user-search/view-search-results-by-page#sample-request)
We default to having 50 entries per_page. It also seems like there's a 1000 entry limit which is unfortunate.
No proper pagination
=> feat: Auth0 add pagination

.github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, Cargo.lock, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
Updates pgrx to 0.11.3 to unblock nix builds on aarch64
=> Bump pgrx to 0.11.3 for 0.3.1 release

supabase-wrappers/src/options.rs
2 changes which are minor  refactor of the code.
1.  Use ok_or_else instead of ok_or. This change prevents the string allocation happening on every method call to only happen when there is an error.
2. SImplify nested if else block `check_option_contain` method. Also use format! macro to prevent to have only one string allocation instead of 2.
No change in behaviour
Please link any relevant issues here.
No change in behaviour
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
=> Minor changes to options file

wrappers/src/fdw/auth0_fdw/auth0_client/row.rs, wrappers/src/fdw/cognito_fdw/cognito_client/rows_iterator.rs
This code is to improve code quality as per clippy suggestion.
N/A
N/A
N/A
=> fix: code improvements as per clippy

docs/clickhouse.md
This PR is to add `secure=true` parameter for ClickHouse Cloud connection string example, as ClickHouse Cloud uses SSL for native collection.
N/A
N/A
N/A
=> docs(clickhouse): add `secure=true` for ClickHouse connection string example

supabase-wrappers/src/interface.rs
This PR is to fix numeric cell's string `display`, which shouldn't use debug format. For example, a numeric cell `Cell::Numeric(123.45)` should display as `123.45`.
This PR also used `BuiltinOid::ForeignDataWrapperRelationId` to replace legacy temporary const definition, as it has been added in upstream.
N/A
N/A
N/A
=> fix: numeric cell display

wrappers/src/fdw/mssql_fdw/mod.rs, wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/mssql_fdw/tests.rs
This PR is to fix #262 , which is caused by incorrect translation from PG sql dialect to T-SQL syntax when using `LIMIT..OFFSET` clause.
The SQL with `LIMIT..OFFSET` clause will be deparsed to `offset 0 rows fetch next .. rows only`, but it needs `ORDER BY` clause to be presented in T-SQL while it is not necessary in Postgres.
An error will happen when `LIMIT..OFFSET` clause is not with an `ORDER BY` clause.
N/A
=> fix(mssql): incorrect sql deparse for limit and offset clause

wrappers/dockerfiles/auth0/server.py, wrappers/src/fdw/auth0_fdw/auth0_client/row.rs, wrappers/src/fdw/auth0_fdw/tests.rs
This PR extends the Auth0User struct to include all fields that the Auth0 endpoint may send (see [Auth0 API Documentation](https://auth0.com/docs/api/management/v2/users/get-users#response-messages)).
N/A
The Auth0User struct now includes all possible fields, allowing us to use these fields in a foreign table and apply quals.
N/A
=> Feat: Extend the fields for users in the Auth0 FDW

supabase-wrappers/src/interface.rs, wrappers/src/fdw/mssql_fdw/tests.rs
This PR is to fix `LIKE` operator qual deparse, which will fix #278 .
Currently, the `LIKE` operator is translated to its original presentation `~~`, which caused error when deparsing qual.
Translate `LIKE` and `NOT LIKE` to sql `like` and `not like` correctly.
N/A
=> fix: deparse LIKE operator in qual

docs/bigquery.md, docs/mssql.md, docs/s3.md, supabase-wrappers/src/interface.rs, wrappers/src/fdw/airtable_fdw/result.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/s3_fdw/parquet.rs
This PR is to add a new column type `timestamp with time zone` support. With this new column type, below FDWs can support the new data type.
- Airtable
- BigQuery
- MS SQL Server
- S3 parquet
- Logflare
Currently only `timestamp without time zone` is supported.
Support `timestamp with time zone` in the framework.
N/A
=> feat: add timestamp with time zone cell type support

Cargo.lock, supabase-wrappers-macros/Cargo.toml, supabase-wrappers/Cargo.toml
This PR is to bump `supabase-wrappers` version to `0.1.18`, and `supabase-wrappers-macros` version to `0.1.16`. After this new versions released on crates.io, it should fix #252 .
N/A
N/A
After this PR is merged, need to manually release the new versions on crates.io.
=> chore: bump supabase-wrappers and supabase-wrappers-macros version

wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/s3_fdw/parquet.rs
This PR is to replace deprecated method `chrono::NaiveDateTime::timestamp` with `.and_utc().timestamp()`, which is suggested by clippy.
N/A
N/A
N/A
=> fix: replace deprecated `chrono::NaiveDateTime::timestamp` method

wrappers/src/stats.rs
This PR is to remove `unwrap()` call from stats related functions. This also caused failure when using API to access foreign tables in some cases.
Currently, it is hard to troubleshot when the panic is caused by `unwrap()` call.
Replace `unwrap()` with `expect()` or remove it if possible.
N/A
=> fix: remove `unwrap()` from stats related functions

wrappers/src/fdw/cognito_fdw/cognito_client/row.rs
This PR is to add `#[allow(dead_code)]` to suppress clippy warning.
N/A
N/A
N/A
=> fix: allow dead code to make clippy happy

.github/workflows/release_wasm_fdw.yml
This PR is to add Wasm FDW release CI workflow. This workflow will be triggered by pushing tag like `wasm_[project name]_[version]`, for example `wasm_snowflake_fdw_v1.0.2`.
Currently there is no CI for Wasm FDW release.
When pushing tag like `wasm_snowflake_fdw_v1.0.2`, the action will build the project Wasm file and create a release for it. This release will be used for Wasm FDW distribution, that is, we can use it in foreign server option like below:
```sql
create server snowflake_server
foreign data wrapper wasm_wrapper
options (
fdw_package_url 'https://github.com/supabase/wrappers/releases/download/wasm_snowflake_fdw_v0.1.0/snowflake_fdw.wasm',
fdw_package_name 'supabase:snowflake-fdw',
fdw_package_version '0.1.0',
...
);
```
N/A
=> ci: add Wasm FDW release workflow

docs/stripe.md, wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to add a new `api_version` foreign server option for Stripe FDW. Fix #291 .
The current Stripe API requests are always using latest Stripe API version, which can cause issues when requesting legacy Stripe API.
Add a new `api_version` foreign server option, so users can specify a specific Stripe API version number when creating a foreign server.
More details about Stripe API versioning: https://docs.stripe.com/api/versioning
N/A
=> feat(stripe): add `api_version` server option

docs/paddle.md, docs/snowflake.md
This PR is to correct wasm file links used in Wasm FDW docs.
Note the Wasm FDWs will be released with tags like below:
```
wasm_<source_name>_fdw_v1.2.3
```
so the download link will be like:
```
https://github.com/supabase/wrappers/releases/download/wasm_<source_name>_fdw_v1.2.3/<source_name>_fdw.wasm
```
Those `.wasm` file links in docs are incorrect.
Use real correct links in the docs.
N/A
=> docs: correct wasm file links in docs

wrappers/Cargo.toml
This PR is to exclude Notion FDW from next release, as it is not mature enough and we will rewrite it using the new Wasm framework.
N/A
Exclude Notion FDW just for now.
N/A
=> chore(notion): exclude notion fdw from next release

.github/workflows/release.yml, Cargo.lock, wrappers/Cargo.toml
This PR is to bump Wrappers version to `0.4.0`.
N/A
N/A
N/A
=> chore: bump version to 0.4.0

wrappers/src/fdw/wasm_fdw/README.md, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
This PR is to fix an issue with wasm package cache dir creation.
The wasm foreign data wrapper (.wasm file) will be downloaded and saved to local cache folder when foreign table is queried. If the local cache doesn't exist yet, this operation will fail.
Create the local cache folder if it doesn't exist before save the wasm file.
This PR also added README and change logs for wasm foreign data wrapper.
=> fix(wasm): missing wasm package cache dir creation

wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
This PR is to add current user id and package url to wasm fdw local cache file name hash, which is to mitigate a security issue described below.
The current wasm fdw local cache file name hash is calculated as `sha256('<pacakge_name>@<version>')`, this will cause a potential security risk. Suppose both user A and B can create foreign table on same database, and then below steps can cause data leaking:
1. user A create a normal foreign table using `package_name=foo, version=1.2.3`, but doesn't query it so the wasm fdw file hasn't been downloaded yet
2. user B made a malicious wasm fdw with the same package name `foo` and version `1.2.3`, this wasm fdw used the same code as user A used, but added an secret code which can post every response to user B controlled data collection site
3. user …
=> fix(wasm): add user id to wasm cache file hash

docs/paddle.md, docs/snowflake.md, wrappers/src/fdw/wasm_fdw/README.md, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
This PR is to add `fdw_package_checksum` server option support. 
Currently the remote Wasm package is specified by package name, url and version. This package content isn't checked so it is vulnerable to the security issue mentioned in #301 .
Add `fdw_package_checksum` server option will make the Wasm package content been checked after download, thus can further protect it from the security issue mentioned above.
Note this `fdw_package_checksum` server option is only required for `http://` and `https://` package url, for local file and `warg` protocol the checksum isn't required.
=> feat(wasm): add `fdw_package_checksum` server option

docs/stripe.md
This PR is to add example code for Stripe data insertion with sub-fields. Fix #288.
N/A
N/A
N/A
=> docs(stripe): add example for data insertion

.github/workflows/release.yml
This PR is to automate the extension upgrade scripts creation.
When a new version is released, we need to manually change the `release.yml` workflow to add a command for previous version upgrade script. Although this manual process is written in playbook, it is tedious and sometimes missed during release. If a certain version upgrade script is missing, it will cause upgrade issue for database with that legacy version of wrappers.
Add a shell script to automate the upgrade script creation process, so it won't missing any previous version upgrade script.
N/A
=> ci: automate extension upgrade scripts creation

supabase-wrappers/src/import_foreign_schema.rs, supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs
This patch add support for the `IMPORT FOREIGN SCHEMA` command.
Closes https://github.com/supabase/wrappers/issues/175
Feel free to include screenshots if it includes visual changes.
=> Add support for IMPORT FOREIGN SCHEMA

.github/workflows/release_wasm_fdw.yml
This PR is to add `checksum.txt` and `README.txt` to WASM FDW release files.
Currently, the WASM FDW release only includes one `.wasm` file.
In the new CI, each WASM FDW release will contain 2 more files: `checksum.txt` and `README.txt`. For example:
- checksum.txt
```
ca487cb169e2b60634900bfb3171834d593e167545dc1144315edfb498049091 ./wasm-wrappers/fdw/paddle_fdw/target/wasm32-unknown-unknown/release/paddle_fdw.wasm
```
- README.txt
```
To use this Wasm foreign data wrapper on Supabase, create a foreign server like below,
create extension if not exists wrappers with schema extensions;
create foreign data wrapper wasm_wrapper
handler wasm_fdw_handler
validator wasm_fdw_validator;
create server example_server
foreign data wrapper wasm_wrapper
options (
fdw_package_url …
```
=> ci: add checksum and README for WASM FDW release

supabase-wrappers/src/import_foreign_schema.rs, supabase-wrappers/src/instance.rs, supabase-wrappers/src/interface.rs, supabase-wrappers/src/modify.rs, supabase-wrappers/src/scan.rs
`import_foreign_schema()` is now a method instead of static method that receives the server id.
=> Change import_foreign_schema() signature.

supabase-wrappers/src/import_foreign_schema.rs
I checked that this fixes the issue on ARM Linux by using a Docker container on a M2 Mac.
Closes https://github.com/supabase/wrappers/issues/318.
=> Fix type of return value for import_foreign_schema()

docs/guides/create-wasm-wrapper.md, docs/guides/query-pushdown.md, docs/guides/wasm-advanced.md, docs/index.md
This PR is to fix broken image links in docs.
N/A
N/A
N/A
=> fix: doc images broken links

mkdocs.yaml
This PR is to fix broken docs edit link.
It points to `master` branch by default.
It points to `main` branch.
N/A
=> docs: fix docs edit link

supabase-wrappers/src/interface.rs
feature
The Cell type format is fixed. While developing a PR for paradeb, I discovered that types like Bytea or Timestamp might be represented differently in various databases. The fmt function of Cell currently supports only the PostgreSQL style. It would be beneficial for users to define their own formatting function while retaining the qual deparse function.
Bytea in postgres is '\x68656C6C6F' and '\x68\x65\x6C\x6C\x6F' in duckdb. It's not Compatible. etc. 
Users of the crate could implement their own custom formatting for the Cell type
paradedb pr: https://github.com/paradedb/paradedb/pull/1404
[postgres bytea hex fomat](https://www.postgresql.org/docs/current/datatype-binary.html#DATATYPE-BINARY-BYTEA-HEX-FORMAT)
[duckdb bytea hex format](https://duckdb.org/docs/sql/data_types/blob)
=> feat: Add user-defined cell fmt interface

supabase-wrappers/src/instance.rs, supabase-wrappers/src/interface.rs, supabase-wrappers/src/lib.rs, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/auth0_fdw/auth0_fdw.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/cognito_fdw/cognito_fdw.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/helloworld_fdw/helloworld_fdw.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/redis_fdw/redis_fdw.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
The complete SQL command to create a foreign data wrapper is 
```
CREATE SERVER [ IF NOT EXISTS ] server_name [ TYPE 'server_type' ] [ VERSION 'server_version' ]
FOREIGN DATA WRAPPER fdw_name
[ OPTIONS ( option 'value' [, ... ] ) ]
```
At this time only the options are given to the Foreign Data Wrapper implementation. This patch changes the signature of `ForeignDataWrapper::new()` to give it the full structure that matches PostgreSQL ForeignServer to expose the server_name, server_type and server_version attributes.
=> Give the full server struct to the FDW when instanciating it

wasm-wrappers/fdw/helloworld_fdw/Cargo.toml, wasm-wrappers/fdw/paddle_fdw/Cargo.toml, wasm-wrappers/fdw/snowflake_fdw/Cargo.toml
This PR is to upgrade 3 wasm fdws to v0.1.1, as their host requirement has been changed in #303 . No business logic change in this upgrade. This upgrade will also use the latest wasm fdw release workflow, so `README.txt` and `checksum.txt` file will be part of this new release.
N/A
N/A
After this PR is merged, need to run below commands to do release:
```bash
git tag wasm_paddle_fdw_v0.1.1
git push origin wasm_paddle_fdw_v0.1.1
git tag wasm_snowflake_fdw_v0.1.1
git push origin wasm_snowflake_fdw_v0.1.1
```
=> chore: upgrade wasm fdws to v0.1.1

docs/catalog/wasm/index.md, mkdocs.yaml
This PR is to reorganize fdw catalog nav, split them into: native and wasm.
N/A
=> docs: reorganize fdw catalog nav

Cargo.lock, docs/catalog/s3.md, wrappers/Cargo.toml, wrappers/src/fdw/s3_fdw/README.md, wrappers/src/fdw/s3_fdw/mod.rs, wrappers/src/fdw/s3_fdw/s3_fdw.rs
This PR is to fix a S3 fdw access issue for Supabase Storage.
The Supabase Storage is S3 compatible but it is using [path-style URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access) access, but current S3 fdw only supports virtual-hosted–style URL requests. This will cause "request failed, service error" error.
Added a new server option `path_style_url` to indicate using path-style URL or not, default is not. When using with Supabase Storage, this option needs to be set to 'true'.
This PR also upgraded some dependencies for S3 fdw. Docs are also updated.
=> fix(s3): Supabase Storage access issue

docs/catalog/stripe.md, supabase-wrappers/src/utils.rs, wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs
This PR is to add `get_vault_secret_by_name()` function in the framework, so fdws can use it to retrieve a secret from Vault by name. This PR will fix #284 .
Currently the Vault secret can only be retrieved by id, which is inconvenient using with db migrations.
Added a new `get_vault_secret_by_name()` function in the framework, so downstream fdws can use it to retrieve a secret from Vault by name.
Stripe FDW has been updated in this PR to add a new server option `api_key_name`, which used the new `get_vault_secret_by_name()` function.
=> feat: add `get_vault_secret_by_name()` function

Cargo.lock, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
- supabase-wrappers -> v0.1.19
- wrappers -> v0.4.2
N/A
N/A
N/A
=> chore: bump version to 0.4.2

README.md, wrappers/src/fdw/airtable_fdw/README.md, wrappers/src/fdw/bigquery_fdw/README.md, wrappers/src/fdw/clickhouse_fdw/README.md, wrappers/src/fdw/cognito_fdw/README.md, wrappers/src/fdw/logflare_fdw/README.md, wrappers/src/fdw/mssql_fdw/README.md, wrappers/src/fdw/notion_fdw/README.md, wrappers/src/fdw/redis_fdw/README.md, wrappers/src/fdw/s3_fdw/README.md, wrappers/src/fdw/stripe_fdw/README.md
This PR is to fix all docs website link in README files as we've moved to the new docs website: https://fdw.dev/.
N/A
N/A
N/A
=> docs: fix docs website link in README

Cargo.lock, docs/catalog/clickhouse.md, wrappers/Cargo.toml, wrappers/src/fdw/clickhouse_fdw/README.md, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is to add `Nullable<T>` data type support for Clickhouse FDW.
Currently `Nullable<T>` data type is not supported.
`Nullable<T>` data type is supported.
This PR also upgraded dependent Clickhouse client lib.
=> feat(clickhouse): add Nullable data type support

docs/catalog/clickhouse.md
This PR fixes the angle brackets in the docs for Clickhouse.
The docs use `Nullable<T>` but markdown table handle angle brackets badly.
This PR changes the docs to use `&lt;` and `&gt;` instead.
Breaks all deployments of the `docs` app because the Clickhouse docs are fetched during each build.
=> docs: Update the nullable to use escaped angle brackets

supabase-wrappers/src/interface.rs, supabase-wrappers/src/qual.rs, wrappers/src/fdw/mssql_fdw/README.md, wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/mssql_fdw/tests.rs
This PR is to add boolean test qual support to Wrappers. Fix #340 .
Currently, the boolean test quals, like `bool_col is true` or `bool_col is not false`, are not supported by Wrappers.
Added support for boolean test quals. The qual `is_admin is active` is parsed like `Qual { field: "is_admin", operator: "is", value: Cell(Bool(true)), use_or: false, param: None }`.
Mssql FDW is changed to adopt this new feature.
=> feat: add boolean test qual support

supabase-wrappers/src/interface.rs, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs, wrappers/src/fdw/bigquery_fdw/mod.rs, wrappers/src/fdw/wasm_fdw/bindings.rs
This PR is to add `Array` cell type support.
Currently array cell type isn't supported.
Add below array cell types support to framework.
- BoolArray
- I16Array
- I32Array
- I64Array
- F32Array
- F64Array
- StringArray
N/A
=> feat: add array cell type support

docs/catalog/stripe.md, wrappers/.ci/docker-compose-native.yaml, wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
This PR is to add [`Meters`](https://docs.stripe.com/api/billing/meter) object for Stripe FDW. Fix #345 
N/A
N/A
This PR also upgrades Stripe mock container to latest version and updated test cases accordingly.
=> feat(stripe): add `Meters` object for Stripe FDW

Cargo.lock, supabase-wrappers-macros/Cargo.toml, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
supabase-wrappers -> v0.1.20
supabase-wrappers-macros -> v0.1.17
wrappers -> v0.4.3
N/A
N/A
N/A
=> chore: bump version to 0.4.3

Cargo.lock, wrappers/Cargo.toml, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
This PR is to upgrade Wasm runtime `wasmtime` version to latest 26.0.0.
The old version of `wasmtime` v21.0.2 not working properly with Rust version > 1.81.0
`wasmtime` version is upgraded to latest 26.0.0, which is compatible with latest version of Rust.
N/A
=> chore(wasm): upgrade wasmtime version to 26.0.0

docs/catalog/redis.md
Docs update - Grammar fix in Redis documentation
In the Redis documentation (docs/catalog/redis.md), there is a grammatical error where the plural "values" doesn't match with the singular "column":
"All Redis value will be stored as `text` or `jsonb` column in Postgres"
Fixed the grammatical issue by using plural forms:
"All Redis values will be stored as `text` or `jsonb` columns in Postgres"
None
=> docs: fix spelling

docs/catalog/notion.md
This PR is to update the Notion Wasm FDW checksum in its doc.
N/A
N/A
N/A
=> docs(notion): update notion wasm fdw checksum

Cargo.lock, docs/catalog/redis.md, wrappers/Cargo.toml, wrappers/src/fdw/redis_fdw/README.md, wrappers/src/fdw/redis_fdw/redis_fdw.rs
This PR is to add TLS connection support to Redis FDW, fix #368 .
The current Redis FDW doesn't support TLS connection `rediss://` in URL.
Added TLS connection support to URL, also with optional `insecure` mode.
- because there is no way to upload files to Wrappers, the client certificate and custom root certificates are not supported when using TLS.
- `redis` dependency lib is also upgraded to `0.27.5`
=> feat(redis): add TLS connection support to Redis FDW

.github/workflows/release_wasm_fdw.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml
This PR is to fix Rust toolchain and Wasm Component version in github workflow.
The current workflows didn't fix Rust toolchain and Wasm Component version, so they used latest version which may not compatible with existing Wasm Wrappers.
Fix Rust toolchain version to `1.81.0` and Wasm Component version to `0.13.2` in workflow so we can make sure get same result each time the workflow runs. 
After this PR is merged, we need to redo release for below Wasm FDWs as they were release with latest version of Rust which isn't compatible with Wrappers 0.4.3.
- Notion Wasm FDW 
- Calendly Wasm FDW 
- Cal.com Wasm FDW
=> ci: fix rust toolchain and component version

wrappers/src/fdw/wasm_fdw/host/mod.rs
This PR is to add a missing type oid for `TIMESTAMPTZOID` data type. Fix #373 .
The `TIMESTAMPTZOID` type is missed in `type_oid()` function.
Add missing `TIMESTAMPTZOID` type oid,
N/A
=> fix(wasm): add missing `TIMESTAMPTZOID` type oid

wrappers/src/fdw/wasm_fdw/mod.rs, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
Bug fix
When loading a wasm file (from the local filesystem), the error message could be used to enumerate files on the filesystem.
File exists - `/etc/passwd`
```
wrappers=# select * from wasm_out;
ERROR:  wasmtime error: failed to parse WebAssembly module
```
No such file - `/etc/nop`
```
wrappers=# select * from wasm_out;
ERROR:  wasmtime error: failed to read input file: /etc/nop
```
Gives a generic error message for file load failures to prevent file system enumeration.
File exists - `/etc/passwd`
```
wrappers=# select * from wasm_out;
ERROR:  wasmtime error: failed to parse WebAssembly module
```
No such file - `/etc/nop`
```
wrappers=# select * from wasm_out;
ERROR:  wasmtime error: failed to parse WebAssembly module
```
Add any other context or screenshots.
=> chore: generic error message for file load

docs/catalog/cal.md, docs/catalog/index.md, wasm-wrappers/fdw/cal_fdw/src/lib.rs
This PR is to add data insertion support for `booking` object in Cal.com wrapper, so we can directly make a booking on Cal.com from Postgres database.
N/A
N/A
As `0.1.0` version number hasn't been officially released, it will be reused.
=> feat(cal): add booking insertion support

docs/catalog/cal.md
This PR is to update Cal.com wasm fdw checksum in its document. This fdw has been added `booking` insertion support in #380 and hasn't been officially released, so we redo the release and reuse the same version number.
N/A
N/A
N/A
=> docs(wasm): update Cal.com wrapper wasm fdw checksum

docs/catalog/cfd1.md
This PR is to update checksum for Cloudflare D1 Wasm FDW, as it has been released https://github.com/supabase/wrappers/releases/tag/wasm_cfd1_fdw_v0.1.0.
N/A
N/A
N/A
=> docs(wasm): update Cloudflare D1 Wasm FDW checksum

docs/catalog/auth0.md
docs update
Accidentally references Airtable in the Auth0 docs
fixed typo
=> Update auth0.md | removed reference to AirTable

Cargo.lock, wrappers/Cargo.lock
This PR is to upgrade dependency hashbrown to 0.15.1, which is to suppress https://github.com/supabase/wrappers/security/dependabot/53. 
N/A
N/A
N/A
=> fix: upgrade hashbrown to 0.15.1

Cargo.lock, wrappers/Cargo.toml
wrappers -> v0.4.4
N/A
N/A
N/A
=> chore: bump version to 0.4.4

.github/workflows/test_wrappers.yml
This PR is to fix Rust toolchain to version 1.81.0 in Wasm wrappers testing CI pipeline. Fix testing issue in #399 .
N/A
N/A
N/A
=> ci: fix Rust version to 1.81.0 for Wasm wrappers test

.github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, Cargo.lock, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
This PR is to upgrade dependency pgrx to `v0.12.7`.
Pgrx is on `v0.12.6`.
Pgrx is upgraded to `v0.12.7`.
N/A
=> chore: upgrade pgrx to 0.12.7

supabase-wrappers/src/interface.rs
This PR is to add `time` data type support to the framework.
No `time` data type support, only support `date`, `timestamp` and `timestamptz` data type.
`time` data type is supported.
N/A
=> feat: add `time` data type support

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml
This PR is to make Rust 1.81.0 as the default toolchain in CI workflow, so to make the WASM fdw built is compatible with wasmtime host.
In the step `actions-rs/toolchain@v1`, the default toolchain is still `stable` although we specified the rust version 1.81.0.
Not only specify the rust version to 1.81.0, we also need to make it the default toolchain so the following steps are using the correct version of rust.
N/A
=> ci: make rust 1.81.0 as the default toolchain

Cargo.lock, docs/catalog/bigquery.md, wrappers/Cargo.toml, wrappers/src/fdw/bigquery_fdw/README.md, wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs
This PR is to add JSON data type support for BigQuery FDW. Ref: #70 
The current BigQuery FDW doesn't support JSON data type.
JSON data type is supported in both reading and modifying.
- Dependent 3rd-party libs are also upgraded to enable the JSON data type support.
- As the dependency lib interface changed, this FDW also did some minor refactoring.
=> chore(bigquery): add JSON data type support

wrappers/.ci/docker-compose-native.yaml, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is to set login credentials used for clickhouse testing.
The current login credentials for clickhouse isn't set, so it defaults to username=default and no password, but latest clickhouse container doesn't hold that true.
Explicitly set login credentials for clickhouse container so the test can success.
N/A
=> ci: set login credentials for clickhouse testing

supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
This PR is to change Rust lints cfgs from `allow` to `warn`.
The current Rust lints cfgs is `allow`, which is not necessary and `warn` level is enough.
Rust lints cfgs is changed to `warn` level.
N/A
=> chore: change Rust lints cfgs to warn

docs/catalog/clerk.md
This PR is to update Clerk FDW v0.1.0 checksum in docs, as it was just released: https://github.com/supabase/wrappers/releases/tag/wasm_clerk_fdw_v0.1.0
N/A
N/A
N/A
=> docs(wasm): update Clerk FDW v0.1.0 checksum in docs

docs/catalog/notion.md, wasm-wrappers/fdw/notion_fdw/src/lib.rs
This PR is adjust page children blocks order for Notion FDW, fix #408.
The current returned children blocks order is based on which API request was completed first, which is not actual order in Notion.
Adjust the returned children blocks order to depth-first ordering, so to make it same as displayed in Notion.
Minor changes are also done for Notion FDW docs.
=> fix(wasm): adjust page children blocks order for Notion FDW

wrappers/src/fdw/mssql_fdw/README.md, wrappers/src/fdw/mssql_fdw/mod.rs, wrappers/src/fdw/mssql_fdw/mssql_fdw.rs, wrappers/src/fdw/mssql_fdw/tests.rs
This PR is to fix the numeric data type conversion precision loss issue in MSSQL FDW, fix #416.
The `numeric` data type is converted to integer, which caused precision loss.
Use `f64` as the converted data type, so to keep number precision.
N/A
=> fix(mssql): numeric data type conversion precision loss

docs/catalog/airtable.md
This PR is to add `Supported Data Types` section to Airtable FDW doc.
N/A
N/A
N/A
=> docs(airtable): add supported data types section

Cargo.lock, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
- wrappers version to `0.4.5`
- supabase-wrappers version to `0.1.21`
N/A
N/A
N/A
=> chore: bump Wrappers version to 0.4.5

docs/catalog/stripe.md, wrappers/src/fdw/stripe_fdw/README.md, wrappers/src/fdw/stripe_fdw/stripe_fdw.rs, wrappers/src/fdw/stripe_fdw/tests.rs
This PR is to add `import foreign schema` support to Stripe FDW.
Currently we have to manually create all the foreign tables with DDL specified in the docs.
We can use `import foreign schema` SQL to automatically import all foreign table definitions. For example,
```sql
-- create all the foreign tables
import foreign schema stripe from server stripe_server into stripe;
-- or, create "checkout_sessions", "customers" and "balance" tables only
import foreign schema stripe
limit to ("checkout_sessions", "customers", "balance")
from server stripe_server into stripe;
-- or, create all foreign tables except "checkout_sessions" and "billing_meters"
import foreign schema stripe
except ("checkout_sessions", "billing_meters")
from server stripe_server into stripe;
```
ATM, this feature is for Stripe …
=> feat(stripe): [DATAENG-875] add schema import support to Stripe FDW

.github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml
Small fix to some actions with explicit GITHUB_TOKEN permissions
=> fix: explicitly define permissions in actions

docs/catalog/airtable.md, docs/catalog/auth0.md, docs/catalog/bigquery.md, docs/catalog/cal.md, docs/catalog/calendly.md, docs/catalog/cfd1.md, docs/catalog/clerk.md, docs/catalog/clickhouse.md, docs/catalog/cognito.md, docs/catalog/firebase.md, docs/catalog/hubspot.md, docs/catalog/logflare.md, docs/catalog/mssql.md, docs/catalog/notion.md, docs/catalog/orb.md, docs/catalog/paddle.md, docs/catalog/redis.md, docs/catalog/s3.md, docs/catalog/snowflake.md, docs/catalog/stripe.md
It is now recommended to use `vault.create_secret` to save credential in Vault, this PR is to update all wrappers docs to use that function rather than using `insert into vault.secrets`.
N/A
N/A
N/A
=> docs: [DATAENG-916] update Vault encryption method

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml
This PR is to upgrade github action runner to Ubuntu 24.04 as Ubuntu 20.04 will be deprecated. A larger runner `larger-runner-4cpu` is also used for coverage workflow as it requires more disk space.
Current github action workflows are using Ubuntu 20.04 runner.
Upgrade github action workflows to use Ubuntu 24.04 runner.
Postgres installation steps are also updated for the new runner.
=> ci: upgrade workflow runner to Ubuntu 24.04

docs/catalog/airtable.md, docs/catalog/auth0.md, docs/catalog/bigquery.md, docs/catalog/cal.md, docs/catalog/calendly.md, docs/catalog/cfd1.md, docs/catalog/clerk.md, docs/catalog/clickhouse.md, docs/catalog/cognito.md, docs/catalog/firebase.md, docs/catalog/hubspot.md, docs/catalog/logflare.md, docs/catalog/mssql.md, docs/catalog/notion.md, docs/catalog/orb.md, docs/catalog/paddle.md, docs/catalog/redis.md, docs/catalog/s3.md, docs/catalog/snowflake.md, docs/catalog/stripe.md
This PR is to update docs to reflect the latest recommended way of secret creation in Vault. 
We were using `secret.key_id` to retrieve decrypted text from Vault.
We are using `secret.id` to retrieve decrypted text from Vault and fallback to use `secret.key_id`, so the docs need to be updated to reflect this change.
N/A
=> docs: update docs for secret creation in Vault

docs/catalog/redis.md
This PR is to add SSL/TLS support docs to Redis FDW.
Currently there is no docs for Redis SSL/TLS connection, although the Redis FDW supports it.
Added SSL/TLS connection docs.
N/A
=> docs(redis): add SSL/TLS support docs to Redis FDW [DATAENG-919]

.github/workflows/docs.yml
Add workflow to automatically revalidate the federated docs at supabase.com/docs when the docs/catalog directory is changed.
For more information on docs deployments, see the [deployment playbook](https://github.com/supabase/playbooks/blob/main/playbooks/docs/federated-docs-deploy.md).
=> chore: add workflow for docs deploys

docs/catalog/clickhouse.md
Supabase Docs - [ClickHouse](https://supabase.com/docs/guides/database/extensions/wrappers/clickhouse#connecting-to-clickhouse)
URL updated to be more generic and copy ClickHouse docs
Closes [31857](https://github.com/supabase/supabase/issues/31857) in supabase repo
=> fix: ClickHouse url change

wrappers/src/lib.rs, wrappers/src/stats.rs
This PR improves the codebase documentation and error handling:
- Add comprehensive module-level documentation
- Add detailed function documentation with arguments and return values
- Improve error handling in stats module with proper Result types
- Make error messages more consistent and descriptive
- Rename constants for better clarity (e.g. WRAPPERS_STATS_TABLE_NAME)
These changes are non-breaking and only improve code maintainability and developer experience. No functional changes were made.
All existing functionality remains unchanged. The improved error handling makes the code more robust and easier to debug.
=> feat: improve documentation and error handling

Cargo.lock, README.md, supabase-wrappers/Cargo.toml, wasm-wrappers/fdw/cal_fdw/src/lib.rs, wasm-wrappers/fdw/calendly_fdw/src/lib.rs, wasm-wrappers/fdw/cfd1_fdw/src/lib.rs, wasm-wrappers/fdw/clerk_fdw/src/lib.rs, wasm-wrappers/fdw/helloworld_fdw/src/lib.rs, wasm-wrappers/fdw/hubspot_fdw/src/lib.rs, wasm-wrappers/fdw/notion_fdw/src/lib.rs, wasm-wrappers/fdw/orb_fdw/src/lib.rs, wasm-wrappers/fdw/paddle_fdw/src/lib.rs, wasm-wrappers/fdw/slack_fdw/src/lib.rs, wasm-wrappers/fdw/snowflake_fdw/src/lib.rs, wrappers/Cargo.toml, wrappers/src/fdw/wasm_fdw/README.md, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs
wrappers version: 0.4.6 -> 0.5.0
supabase-wrappers version: 0.1.21 -> 0.1.22
all Wasm wrappers version: 0.1.* -> 0.2.0
N/A
N/A
- Wasm FDW host version is adjusted to `0.1.5` for back compatibility, thus Wasm FDW guests are all adjusted to `~0.1.0` for their host version requirement.
=> chore: bump Wrappers version to 0.5.0

wrappers/wrappers.control
This PR is to make `wrappers` extension relocatable. 
The `wrappers` extension is not relocatable, e.g. `relocatable = false` in .control file.
The `wrappers` extension is relocatable, e.g. `relocatable = true` in .control file.
N/A
=> fix: [DATAENG-969] make wrappers extension relocatable

docs/catalog/auth0.md
This PR is to add the missing `url` server option in Auth0 FDW docs.
N/A
N/A
N/A
=> docs(auth0): add missing `url` server option

Cargo.lock, README.md, docs/catalog/cal.md, docs/catalog/calendly.md, docs/catalog/cfd1.md, docs/catalog/clerk.md, docs/catalog/hubspot.md, docs/catalog/notion.md, docs/catalog/orb.md, docs/catalog/paddle.md, docs/catalog/slack.md, docs/catalog/snowflake.md, supabase-wrappers-macros/Cargo.toml, wrappers/Cargo.toml
This PR is to bump Wrappers version to `0.5.1`.
N/A
N/A
- upstream Iceberg dependency has [merged our patch](https://github.com/apache/iceberg-rust/pull/1347), so we switched back to use the upstream Iceberg
- all the Wasm wrappers v0.2.0 checksum are updated
- a few other minor fixes
=> chore: bump Wrappers version to `0.5.1`

docs/catalog/clickhouse.md, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is to fix some integer data type conversion issues between ClickHouse and Postgres.
Currently some of the integer data types conversion from ClickHouse -> Postgres:
- Bool -> missing
- Int8 -> missing
- UInt8 -> boolean
- Nullable(Bool) -> missing
- Nullable(Int8) -> missing
- Nullable(UInt8) -> boolean
Added some missing data type conversions:
From ClickHouse -> Postgres:
- Bool -> boolean
- Int8 -> "char"
- UInt8 -> smallint
- Nullable(Bool) -> boolean
- Nullable(Int8) -> "char"
- Nullable(UInt8) -> smallint
From Postgres -> ClickHouse, according to the target column type, we do below down casting:
- smallint -> UInt8
- integer -> UInt16
- bigint -> UInt32
N/A
=> fix(clickhouse): integer type up-cast and down-cast

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/src/import_foreign_schema.rs, supabase-wrappers/src/modify.rs, supabase-wrappers/src/scan.rs, supabase-wrappers/src/utils.rs, wrappers/Cargo.toml, wrappers/src/fdw/airtable_fdw/tests.rs, wrappers/src/fdw/auth0_fdw/tests.rs, wrappers/src/fdw/bigquery_fdw/tests.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs, wrappers/src/fdw/cognito_fdw/tests.rs, wrappers/src/fdw/firebase_fdw/tests.rs, wrappers/src/fdw/iceberg_fdw/tests.rs, wrappers/src/fdw/logflare_fdw/tests.rs, wrappers/src/fdw/mssql_fdw/tests.rs, wrappers/src/fdw/redis_fdw/tests.rs, wrappers/src/fdw/s3_fdw/tests.rs, wrappers/src/fdw/stripe_fdw/tests.rs, wrappers/src/fdw/wasm_fdw/bindings/v1.rs, wrappers/src/fdw/wasm_fdw/bindings/v2.rs, wrappers/src/fdw/wasm_fdw/tests.rs, wrappers/src/fdw/wasm_fdw/wasm_fdw.rs, wrappers/src/stats.rs
PostgreSQL 12 has been unsupported for over half a year, and pgrx v0.14.0 officially dropped support for it.
The other reason I propose this version bumping is that pgrx v0.12.9 failed to install pg 12 on my mac.
This patch removes PG12 support from the wrappers by upgrading pgrx to v0.14.3. Some code adjustments were required due to changes introduced in the newer pgrx versions.
For reference, see the following updates in pgrx:
- [force using extern "C-unwind" for functions marked with `#[pg_guard]`][1]
- [Made SPI query arguments type safe][2]
- [Added connect_mut for data changing SPI operations][3]
- [Renamed Oid::as_u32 to to_u32][4]
[1]: https://github.com/pgcentralfoundation/pgrx/pull/2014
[2]: https://github.com/pgcentralfoundation/pgrx/pull/1858
[3]: …
=> chore: bump pgrx to v0.14.3

supabase-wrappers/src/memctx.rs, supabase-wrappers/src/modify.rs, supabase-wrappers/src/scan.rs, supabase-wrappers/src/utils.rs, wrappers/src/fdw/stripe_fdw/tests.rs
This PR is to do some memory context layout refactoring in the Wrappers framework.
The current memory context layout in the framework is like below:
- CacheMemoryContext
- WrappersRootMemCtx (long-live)
- Wrappers_scan_xxx (long-live)
- Wrappers_scan_yyy (long-live)
- Wrappers_modify_xxx (long-live)
- ...
Each foreign table has exactly one scan and modify memory context with its oid as name suffix. Those memory context are created under the single root `WrappersRootMemCtx` which is under `CacheMemoryContext`.
The memory context will never be deleted after creation, but it will be reset at the beginning of the query, in `GetForeignRelSize` (scan) and `PlanForeignModify` (modify) callbacks respectively.
This caused problem when a query has multiple foreign scans planned and those callbacks …
=> fix: [DATAENG-979] memory context layout refactoring

Cargo.lock, docs/catalog/iceberg.md, wrappers/Cargo.toml, wrappers/src/fdw/iceberg_fdw/README.md, wrappers/src/fdw/iceberg_fdw/iceberg_fdw.rs, wrappers/src/fdw/iceberg_fdw/tests.rs
This PR is mainly to refactor how the server options passed down to iceberg crate.
Currently, only a few hand-picked options in `create server` are passed down to iceberg crate. Those options are not comprehensive and have unnecessary name translation.
All the options in `create server` are passed down to iceberg crate without modification, except the option has `vault_` prefix, which will be replaced by decrypted text from Vault and the name striped that prefix. With this change, we can support any the iceberg services as upstream supported.
Other changes in this PR:
- As upstream iceberg crate just released version `0.5.1`, we switched to use it
- Upstream S3 tables catalog crate hasn't released yet, so we used a fork of it
- Updated docs and added one more example `Read Cloudflare R2 …
=> fix(iceberg): refactor sever options passdown

.github/workflows/test_wrappers.yml, Cargo.lock, wrappers/Cargo.toml
This PR is to bump Wrappers version to 0.5.3. This a fix version which is to include the missing DuckDB FDW.
N/A
N/A
Upgrade CI runner spec as the original one is too small.
=> chore: bump wrappers version to `0.5.3`

wrappers/src/fdw/iceberg_fdw/iceberg_fdw.rs
This PR is to remove server option validator for Iceberg FDW.
The current server option validator requires both `aws_access_key_id` and `aws_secret_access_key` to be presented, but those options are not mandatory anymore because this FDW can connect to Iceberg services other than AWS.
Removed those 2 server options requirement.
N/A
=> fix(iceberg): remove server option validator

wrappers/src/fdw/iceberg_fdw/README.md, wrappers/src/fdw/iceberg_fdw/iceberg_fdw.rs, wrappers/src/fdw/iceberg_fdw/mapper.rs
This PR is to improve the performance for large data set query. The optimisations includes:
- changed `IcebergFdw.predicate` to `Option<Predicate>`, and only apply it to a scan if it is not None
- convert batch to cells in whole once the batch is fetched, rather than convert each row one by one in `iter_scan`
- move the stats data writing to the end of `iter_scan`, so it will run once only
- added a new `batch_size` server option to specify record batch size, default is 4096
For a 50M records source data set on Supabase Storage, the query `select count(order_id) from iceberg.orders` will take about 5 min 50 seconds.
The same query will take about 40 seconds.
=> perf(iceberg): improve large data set query performance

supabase-wrappers/src/interface.rs, wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs, wrappers/src/fdw/clickhouse_fdw/tests.rs
This PR is to prevent array type qual to be pushed down for ClickHouse FDW. Fix #491.
Array type operators, such like `@>`, are not supported by ClickHouse, but they are included in the deparsed sql and pushed down to ClickHouse.
Wrappers won't do array operator translation, so all array type column quals are excluded from pushdown.
N/A
=> fix(clickhouse): exclude array type qual pushdown

Cargo.lock, docs/catalog/duckdb.md, wrappers/Cargo.toml, wrappers/src/fdw/duckdb_fdw/README.md, wrappers/src/fdw/duckdb_fdw/duckdb_fdw.rs
This PR is to replace `execute_batch()` with `execute()` used in DuckDB wrapper. 
The `execute_batch()` can run multiple sql in one batch, but it won't report error if one of it failed. This might be a bug in upstream.
To mitigate this issue we run each sql separately using `execute()` so the error will be reported correctly.
Some other minor changes in this PR:
- upgrade upstream DuckDB crate version to `1.3.2`
- some doc errors are fixed as well
=> fix(duckdb): replace `execute_batch()` with `execute()`

Cargo.lock, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
This PR is to bump wrappers version to 0.5.4.
N/A
N/A
supabase-wrappers framework version is also upgraded to 0.1.23.
=> chore: bump wrappers version to 0.5.4

.github/workflows/release.yml
This PR is to upgrade Ubuntu 20 based arm runner to Ubuntu 24 based `u22-arm-runner`.
N/A
N/A
N/A
=> ci: upgrade arm runner to `u22-arm-runner`

.github/workflows/release_wasm_fdw.yml
This PR is to fix the incorrect wasm file path when creating a Wasm FDW release.
The wasm file target path uses each individual wasm fdw target folder, which is incorrect as all the wasm fdws are now under a workspace. The target folder is now under the workspace.
Use the workspace target folder as wasm file path.
N/A
=> ci: fix wasm file path when creating release

.github/workflows/release_wasm_fdw.yml
The PR is to fix another similar issue as #498 , the input of checksum file generation should be the workplace folder.
N/A
N/A
N/A
=> ci: fix checksum file generation in Wasm FDW release workflow

supabase-wrappers/src/interface.rs
This PR is to fix incorrect NULL processing in FromDatum implementation for `bytea` type in Cell.
It didn't deal with NULL case properly and always return NOT NULL.
Deal with NULL case correctly just like other data types.
N/A
=> fix: deal with NULL in FromDatum implementation for `bytea` type in Cell

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, Cargo.lock, supabase-wrappers/Cargo.toml, supabase-wrappers/src/scan.rs, supabase-wrappers/src/sort.rs, wrappers/Cargo.toml
This PR is to add support for Postgres v18, and also upgraded `pgrx` to `0.16.0`.
Currently no pg18 support.
Pg18 is supported.
N/A
=> chore: add support for pg18

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/release_wasm_fdw.yml, .github/workflows/test_supabase_wrappers.yml, .github/workflows/test_wrappers.yml, Cargo.lock, Cargo.toml, docs/catalog/iceberg.md, docs/catalog/index.md, wrappers/Cargo.toml, wrappers/dockerfiles/s3/Dockerfile, wrappers/dockerfiles/s3/iceberg_seed.py, wrappers/src/fdw/airtable_fdw/airtable_fdw.rs, wrappers/src/fdw/duckdb_fdw/tests.rs, wrappers/src/fdw/firebase_fdw/firebase_fdw.rs, wrappers/src/fdw/iceberg_fdw/README.md, wrappers/src/fdw/iceberg_fdw/iceberg_fdw.rs, wrappers/src/fdw/iceberg_fdw/mapper.rs, wrappers/src/fdw/iceberg_fdw/mod.rs, wrappers/src/fdw/iceberg_fdw/pushdown.rs, wrappers/src/fdw/iceberg_fdw/tests.rs, wrappers/src/fdw/iceberg_fdw/utils.rs, wrappers/src/fdw/iceberg_fdw/writer.rs, wrappers/src/fdw/logflare_fdw/logflare_fdw.rs, wrappers/src/fdw/redis_fdw/redis_fdw.rs
This PR is to add `INSERT` support for Iceberg FDW.
Examples:
```sql
-- insert a single record
insert into iceberg.guides (id, title, content, created_at)
values (100, 'New Guide', 'This is a new guide', now());
-- insert multiple records at once
insert into iceberg.guides (id, title, content, created_at)
values
(101, 'Guide A', 'Content for Guide A', now()),
(102, 'Guide B', 'Content for Guide B', now()),
(103, 'Guide C', 'Content for Guide C', now());
-- insert data from a SELECT query
insert into iceberg.guides (id, title, content, created_at)
select
id + 1000,
'Migrated: ' || title,
content,
created_at
from other_guides
where id < 10;
```
Iceberg FDW is read-only.
Iceberg FDW can support `INSERT` now.
This PR also upgraded Rust version to `1.86.0` and fixed several clippy warning …
=> feat(iceberg): [WRA-2] add INSERT support for Iceberg FDW

Cargo.lock, supabase-wrappers/Cargo.toml, wrappers/Cargo.toml
This PR is to bump wrappers version to 0.5.5. 
N/A
Major changes in this version:
- [Added AWS S3 Vectors wrapper](https://github.com/supabase/wrappers/pull/503)
- [Added INSERT support for Iceberg wrapper](https://github.com/supabase/wrappers/pull/506)
- [Added pg18 support](https://github.com/supabase/wrappers/pull/505)
- [Added Shopify Wasm wrapper](https://github.com/supabase/wrappers/pull/497)
N/A
=> chore: bump Wrappers version to 0.5.5

.github/workflows/release.yml, .github/workflows/release_wasm_fdw.yml
This PR is to change release workflow runner to `blacksmith-4vcpu-ubuntu-2404`.
The release runner is `blacksmith-8vcpu-ubuntu-2404`, but it is currently not usable.
Change the release workflow runner to `blacksmith-4vcpu-ubuntu-2404`.
N/A
=> ci: change release runner to `blacksmith-4vcpu-ubuntu-2404`
