supabase-wrappers/src/modify.rs
supabase-wrappers/src/scan.rs

This PR is to change temporary memory context's parent to `CurTransactionContext`, which will fix crash issue when using some SQL client tools, such as DBeaver.
Some SQL client tools, like DBeaver, will change the default `CurrentMemoryContext` which may cause FDW crash as the state structure and its temporary memory context's using `CurrentMemoryContext` as their parent context.
The state structure and its temporary memory context will be fixed to allocate under `CurTransactionContext`.
So far, only DBeaver has this issue, psql and Supabase are not affected.

fix: change memory context parent to CurTransactionContext

---

Cargo.lock
supabase-wrappers/src/lib.rs
wrappers/Cargo.lock

This PR is to update version number in Cargo.lock file and a minor doc update
N/A
N/A
N/A

docs: update Cargo lock file and minor doc update

---

README.md
docs/usage.md
supabase-wrappers/README.md
wrappers/src/fdw/firebase_fdw/README.md
wrappers/src/fdw/stripe_fdw/README.md

I fixed some small typo errors

fix: small typo errors

---

supabase-wrappers/README.md

Fixed broken link in supabase-wrappers/README.md
The link is 404.
N/A

Fix broken link in README

---

wrappers/src/fdw/stripe_fdw/stripe_fdw.rs

Support for accounts and transfers

:sparkles: Support Stripe Connect

---

docs/firebase.md
docs/s3.md

This PR is fix #104 
N/A
N/A
N/A

fix: unnecessary semicolon in docs example

---

.dockerignore
.github/workflows/release.yml
.github/workflows/test_wrappers.yml
wrappers/dockerfiles/firebase/firebase.json

Minor fixes.
- A few config files are not strictly compliant with the corresponding JSON or YAML schemas.
- The PDPG APT repo URL used for downloading the PostgreSQL packages does not use HTTPS.
- A few config files are now strictly compliant with the corresponding JSON or YAML schemas.
- The PDPG APT repo URL used for downloading the PostgreSQL packages uses HTTPS.
None

chore: minor fixes

---

.github/workflows/release.yml
docs/airtable.md
docs/index.md
mkdocs.yaml
wrappers/.ci/docker-compose.yaml
wrappers/Cargo.toml
wrappers/dockerfiles/airtable/Dockerfile
wrappers/dockerfiles/airtable/server.py
wrappers/src/fdw/airtable_fdw/README.md
wrappers/src/fdw/airtable_fdw/airtable_fdw.rs
wrappers/src/fdw/airtable_fdw/result.rs
wrappers/src/fdw/airtable_fdw/tests.rs

This PR is to enhance existing Airtable FDW:
1. Added more data types support
2. Fixed minor bugs
3. Added docs
4. Added test cases
N/A
N/A
N/A

chore: airtable fdw enhancement

---

docs/index.md
docs/logflare.md
mkdocs.yaml
wrappers/Cargo.toml
wrappers/src/fdw/logflare_fdw/README.md
wrappers/src/fdw/logflare_fdw/logflare_fdw.rs
wrappers/src/fdw/logflare_fdw/mod.rs
wrappers/src/fdw/mod.rs

This PR is to add the Logflare FDW.
N/A
N/A
N/A

feat: add logflare fdw

---

README.md
docs/logflare.md
supabase-wrappers/README.md
supabase-wrappers/src/lib.rs
wrappers/README.md
wrappers/src/fdw/logflare_fdw/logflare_fdw.rs

This PR is to improve Logflare code quality:
1. added stats collection for Logflare FDW
2. renamed meta column `_attrs` to `_result` for better column naming
3. update docs
There is no stats collection in Logflare FDW.
Stats collections have been built into Logflare FDW.
N/A

chore: add logflare fdw stats collection and code quality improvement

---

wrappers/src/fdw/airtable_fdw/airtable_fdw.rs

This PR is to add missing `api_key_id` foreign server option for Airtable FDW.
Currently there is no `api_key_id` foreign server option supported.
Support api_key_id` foreign server option so API key can be stored in Vault.
N/A

fix(airtable_fdw): api_key_id server option

---

README.md

I converted the list of current FDWs into a table.

chore: converted list into table

---

.github/workflows/release.yml
.github/workflows/test_wrappers.yml
Cargo.lock
supabase-wrappers/Cargo.toml
supabase-wrappers/src/lib.rs
wrappers/Cargo.lock
wrappers/Cargo.toml

bump pgrx version to 0.9.8

---

.github/workflows/test_supabase_wrappers.yml
.github/workflows/test_wrappers.yml
supabase-wrappers/src/interface.rs
supabase-wrappers/src/lib.rs
supabase-wrappers/src/utils.rs

Fix for doc tests not compiling for the `supabase-wrappers` project.
Doc tests did not compile.
Doc tests compile successfully.
Also added a CI step for running tests (which includes doc tests) for `supabase-wrappers`.

fix: doc test compilation errors

---

wrappers/Cargo.toml
wrappers/src/fdw/stripe_fdw/mod.rs
wrappers/src/fdw/stripe_fdw/stripe_fdw.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor Stripe FDW.
Error reporting is using new facilities in wrappers framework for Stripe FDW.
N/A

chore(stripe_fdw): refactor error reporting

---

wrappers/Cargo.lock
wrappers/Cargo.toml
wrappers/src/fdw/s3_fdw/mod.rs
wrappers/src/fdw/s3_fdw/parquet.rs
wrappers/src/fdw/s3_fdw/s3_fdw.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor S3 FDW.
Error reporting is using new facilities in wrappers framework for Stripe FDW.
N/A

chore(s3_fdw): refactor error reporting

---

wrappers/Cargo.toml
wrappers/src/fdw/logflare_fdw/logflare_fdw.rs
wrappers/src/fdw/logflare_fdw/mod.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor Logflare FDW.
Error reporting is using new facilities in wrappers framework for Logflare FDW.
N/A

chore(logflare_fdw): refactor error reporting

---

supabase-wrappers/src/lib.rs
wrappers/src/fdw/helloworld_fdw/README.md
wrappers/src/fdw/helloworld_fdw/helloworld_fdw.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor HelloWorld FDW.
Error reporting is using new facilities in wrappers framework for HelloWorld FDW.
N/A

chore(helloworld_fdw): refactor error reporting

---

wrappers/src/fdw/firebase_fdw/README.md
wrappers/src/fdw/firebase_fdw/firebase_fdw.rs
wrappers/src/fdw/firebase_fdw/mod.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor Firebase FDW.
Error reporting is using new facilities in wrappers framework for HelloWorld FDW.
N/A

chore(firebase_fdw): refactor error reporting

---

.github/workflows/release.yml
.github/workflows/test_supabase_wrappers.yml
.github/workflows/test_wrappers.yml
Cargo.lock
supabase-wrappers/Cargo.toml
supabase-wrappers/src/lib.rs
wrappers/Cargo.lock
wrappers/Cargo.toml

- bumps pgrx to 0.10.2 for pg16 support
- adds pg16 to release matrix

PG16 Support

---

wrappers/src/fdw/clickhouse_fdw/clickhouse_fdw.rs
wrappers/src/fdw/clickhouse_fdw/mod.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor ClickHouse FDW.
Error reporting is using new facilities in wrappers framework for ClickHouse FDW.
N/A

chore(clickhouse_fdw): refactor error reporting

---

wrappers/src/fdw/bigquery_fdw/bigquery_fdw.rs
wrappers/src/fdw/bigquery_fdw/mod.rs

This PR is to use the new error reporting facilities in wrappers framework to refactor BigQuery FDW.
Error reporting is using new facilities in wrappers framework for BigQuery FDW.
N/A

chore(bigquery_fdw): refactor error reporting

---

wrappers/src/fdw/airtable_fdw/airtable_fdw.rs
wrappers/src/fdw/airtable_fdw/mod.rs
wrappers/src/fdw/airtable_fdw/result.rs

Removes a few `unwrap` calls in the Airtable wrapper.

chore(airtable_fdw): remove a few unwrap calls

---

wrappers/src/fdw/firebase_fdw/firebase_fdw.rs
wrappers/src/fdw/firebase_fdw/mod.rs

Remove a few `unwrap` calls in the Firebase wrapper.

chore(firebase_fdw): remove a few unwrap calls

---

wrappers/src/fdw/logflare_fdw/logflare_fdw.rs
wrappers/src/fdw/logflare_fdw/mod.rs

Remove a few `unwrap` calls in the Logflare fdw.

chore(logflare_fdw): remove a few unwrap calls

---

wrappers/src/fdw/s3_fdw/mod.rs
wrappers/src/fdw/s3_fdw/parquet.rs
wrappers/src/fdw/s3_fdw/s3_fdw.rs

Remove a few `unwrap` calls in the S3 fdw.

chore(s3_fdw): remove a few unwrap calls

---

wrappers/src/fdw/stripe_fdw/mod.rs
wrappers/src/fdw/stripe_fdw/stripe_fdw.rs

Remove a few `unwrap` calls in Stripe fdw.

 chore(stripe_fdw): remove a few unwrap calls

---

docs/stripe.md

Add note in docs to describe the stripe/join issue described in https://github.com/supabase/wrappers/issues/113

Document stripe join issue until its fixed

---

docs/airtable.md
docs/bigquery.md
docs/clickhouse.md
docs/firebase.md
docs/logflare.md
docs/s3.md
docs/stripe.md

This PR is to add documents for pushdown support.
N/A
N/A
N/A

docs: add pushdown support docs

---

.github/workflows/test_supabase_wrappers.yml
.github/workflows/test_wrappers.yml
Cargo.lock
supabase-wrappers/Cargo.toml
wrappers/Cargo.lock
wrappers/Cargo.toml

pgrx recently [released a new version](https://lib.rs/crates/cargo-pgrx)

feat: bump pgrx version

---

docs/contributing.md

Minor statement about notice! calls

docs: update contributing

---

README.md
docs/index.md
docs/mssql.md
mkdocs.yaml
supabase-wrappers/src/lib.rs
wrappers/.ci/docker-compose.yaml
wrappers/Cargo.lock
wrappers/Cargo.toml
wrappers/README.md
wrappers/src/fdw/mod.rs
wrappers/src/fdw/mssql_fdw/README.md
wrappers/src/fdw/mssql_fdw/mod.rs
wrappers/src/fdw/mssql_fdw/mssql_fdw.rs
wrappers/src/fdw/mssql_fdw/tests.rs

This PR is to add a new SQL Server foreign data wrapper, which supports basic data read at this moment.
N/A
N/A
N/A

feat: add sql server foreign data wrapper

---

docs/contributing.md

This PR is to add community Wrappers contribution docs.
N/A
N/A
N/A

docs: add community wrappers contribution docs

---

README.md
docs/index.md
docs/redis.md
mkdocs.yaml
supabase-wrappers/src/lib.rs
wrappers/.ci/docker-compose.yaml
wrappers/Cargo.lock
wrappers/Cargo.toml
wrappers/README.md
wrappers/src/fdw/mod.rs
wrappers/src/fdw/redis_fdw/README.md
wrappers/src/fdw/redis_fdw/mod.rs
wrappers/src/fdw/redis_fdw/redis_fdw.rs
wrappers/src/fdw/redis_fdw/tests.rs

This PR is to add a new Redis foreign data wrapper, which supports basic data read at this moment.
N/A
N/A
N/A

feat: add redis foreign data wrapper

---

Cargo.lock
README.md
wrappers/Cargo.toml

This PR is to bump Wrappers version to `0.4.1`, which fixed an issue #298 
N/A
N/A
N/A

bump version to 0.4.1

---

wrappers/src/fdw/wasm_fdw/wasm_fdw.rs

This PR is to fix typo in checksum checking error message.
N/A
N/A
N/A

fix(wasm): typo in checksum checking error message

---

.github/workflows/release.yml
.github/workflows/test_supabase_wrappers.yml
.github/workflows/test_wrappers.yml
wrappers/.ci/docker-compose.yaml
wrappers/dockerfiles/notion/requirements.txt

This PR is to update docker compose command and upgrade checkout action in CI workflows.
N/A
N/A
This PR also fixed an issue in notion docker.

ci: update docker compose and checkout action

---

docs/guides/create-wasm-wrapper.md

This PR is to fix a typo in the docs.
N/A
N/A
N/A

docs: fix typo

---

supabase-wrappers/src/interface.rs

This PR is to add support for `Uuid` data type in Wrappers framework.
The `Uuid` data type isn't supported in Wrappers framework.
The `Uuid` data type is supported in Wrappers framework, supports in downstream FDWs will be added later individually if required. 
N/A

feat: add Uuid data type support

---

docs/catalog/notion.md

This PR is to update checksum for the Notion Wasm FDW v0.1.1 release: https://github.com/supabase/wrappers/releases/tag/wasm_notion_fdw_v0.1.1.
N/A
N/A
N/A

docs(wasm): upgrade Notion Wasm FDW v0.1.1 checksum

---

docs/catalog/orb.md

This PR is to update checksum for the Orb Wasm FDW v0.1.0 release: https://github.com/supabase/wrappers/releases/tag/wasm_orb_fdw_v0.1.0
N/A
N/A
N/A

docs(wasm): update Orb Wasm FDW v0.1.0 checksum

---

docs/catalog/hubspot.md

This PR is to update checksum for the HubSpot Wasm FDW v0.1.0 release: https://github.com/supabase/wrappers/releases/tag/wasm_hubspot_fdw_v0.1.0
N/A
N/A
N/A

docs(wasm): update HubSpot Wasm FDW v0.1.0 checksum

---

docs/catalog/notion.md

Adds some extra details around getting the Notion api key.

More details on Notion doc

---

wrappers/dockerfiles/bigquery/data.yaml
wrappers/src/fdw/bigquery_fdw/tests.rs
wrappers/src/fdw/cognito_fdw/tests.rs

This PR is to add more test cases for BigQuery and Cognito FDW.
N/A
N/A
N/A

chore: [DATAENG-876] add more bigquery and cognito test cases

---

docs/catalog/cognito.md
wrappers/src/fdw/cognito_fdw/README.md
wrappers/src/fdw/cognito_fdw/cognito_fdw.rs
wrappers/src/fdw/cognito_fdw/tests.rs

This PR is to add schema import support to Cognito FDW.
The schema import isn't supported in Cognito FDW.
The schema import is supported in Cognito FDW.
N/A

feat(cognito): add schema import support to Cognito FDW

---

.github/workflows/coverage.yml

More build concurrency
Not much build concurrency
More build concurrency
Concurrency.

chore: use larger runner group rather than a single larger runner

---

.github/workflows/coverage.yml
.github/workflows/release.yml
.github/workflows/release_wasm_fdw.yml
.github/workflows/test_supabase_wrappers.yml
.github/workflows/test_wrappers.yml

This PR is to switch to use blacksmith runners in CI to speed up the workflows.
N/A
N/A
N/A

ci: use blacksmith runners
